{"id":586,"status":"Fixed","summary":"Type checking error when replacing a function with a stub after calling.","labels":["Type-Defect","Priority-Medium"],"stars":0,"commentCount":3,"comments":[{"id":0,"commenterId":-3418496494830539189,"content":"Given the following Javascript:\r\n\r\n  /** @constructor */\r\n  var myclass \u003d function() {\r\n  }\r\n  \r\n  /** @param {boolean} success */\r\n  myclass.prototype.fn \u003d function(success) { }\r\n  \r\n  myclass.prototype.test \u003d function() {\r\n    this.fn();\r\n    this.fn \u003d function() { };\r\n  }\r\n\r\nI would expect an error at both lines of test(). Instead, the second line causes the error in the first not to be reported.","timestamp":1319738447,"attachments":[]},{"id":1,"commenterId":-7699928860083865744,"content":"thanks for reporting!","timestamp":1320687052,"attachments":[]},{"id":2,"commenterId":-7699928860083865744,"content":"","timestamp":1321304579,"attachments":[]}]}